# Generated by Django 5.1.5 on 2025-01-30 18:17

import cinemas.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Last name"
                    ),
                ),
            ],
            options={
                "verbose_name": "actor",
                "verbose_name_plural": "actors",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "genre",
                "verbose_name_plural": "genres",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("runtime", models.IntegerField(verbose_name="Runtime")),
                ("synopsis", models.TextField(verbose_name="Synopsis")),
                (
                    "want_to_see_count",
                    models.IntegerField(verbose_name="Want to see count"),
                ),
                ("poster", models.URLField(blank=True, verbose_name="Poster")),
                (
                    "cast",
                    models.ManyToManyField(to="cinemas.actor", verbose_name="Cast"),
                ),
                (
                    "director",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_movie_set",
                        to="cinemas.actor",
                        verbose_name="Director",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(to="cinemas.genre", verbose_name="Genres"),
                ),
            ],
            options={
                "verbose_name": "movie",
                "verbose_name_plural": "movies",
            },
        ),
        migrations.CreateModel(
            name="Showtime",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start time")),
                (
                    "theater_id",
                    cinemas.fields.TheaterField(),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinemas.movie",
                        verbose_name="Movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "showtime",
                "verbose_name_plural": "showtimes",
            },
        ),
    ]
